<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class SpeciesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('species')->delete();

        DB::table('species')->insert([

            # 1 - Anfíbios
            [
                'id'             => 1,
                'name'           => 'Perereca',
                'slug'           => str_slug('Perereca'),
                'animal_type_id' => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 2,
                'name'           => 'Sapo',
                'slug'           => str_slug('Sapo'),
                'animal_type_id' => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 3,
                'name'           => 'Outros',
                'slug'           => str_slug('Outros'),
                'animal_type_id' => 1,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            # 2 - Aves
            [
                'id'             => 4,
                'name'           => 'Cacatua',
                'slug'           => str_slug('Cacatua'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 5,
                'name'           => 'Calopsita',
                'slug'           => str_slug('Calopsita'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 6,
                'name'           => 'Canário',
                'slug'           => str_slug('Canário'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 7,
                'name'           => 'Curio',
                'slug'           => str_slug('Curio'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 8,
                'name'           => 'Galinha',
                'slug'           => str_slug('Galinha'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 9,
                'name'           => 'Galo',
                'slug'           => str_slug('Galo'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 10,
                'name'           => 'Papaguaio',
                'slug'           => str_slug('Papaguaio'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 11,
                'name'           => 'Pardal',
                'slug'           => str_slug('Pardal'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 12,
                'name'           => 'Pato',
                'slug'           => str_slug('Pato'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 13,
                'name'           => 'Periquito',
                'slug'           => str_slug('Periquito'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 14,
                'name'           => 'Peru',
                'slug'           => str_slug('Peru'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 15,
                'name'           => 'Outros',
                'slug'           => str_slug('Outros'),
                'animal_type_id' => 2,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            # 3 - Invertebrados
            [
                'id'             => 16,
                'name'           => 'Aranhas',
                'slug'           => str_slug('Aranhas'),
                'animal_type_id' => 3,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 17,
                'name'           => 'Caramujos',
                'slug'           => str_slug('Caramujos'),
                'animal_type_id' => 3,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 18,
                'name'           => 'Carangueijos',
                'slug'           => str_slug('Carangueijos'),
                'animal_type_id' => 3,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 19,
                'name'           => 'Outros',
                'slug'           => str_slug('Outros'),
                'animal_type_id' => 3,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            # 4 - Mamíferos
            [
                'id'             => 20,
                'name'           => 'Boi',
                'slug'           => str_slug('Boi'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 21,
                'name'           => 'Cachorro',
                'slug'           => str_slug('Cachorro'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 22,
                'name'           => 'Camundongo',
                'slug'           => str_slug('Camundongo'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 23,
                'name'           => 'Chinchila',
                'slug'           => str_slug('Chinchila'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 24,
                'name'           => 'Coelho',
                'slug'           => str_slug('Coelho'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 25,
                'name'           => 'Cavalo',
                'slug'           => str_slug('Cavalo'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 26,
                'name'           => 'Gato',
                'slug'           => str_slug('Gato'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 27,
                'name'           => 'Porco da India',
                'slug'           => str_slug('Porco da India'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 28,
                'name'           => 'Ramster',
                'slug'           => str_slug('Ramster'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 29,
                'name'           => 'Vaca',
                'slug'           => str_slug('Vaca'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 30,
                'name'           => 'Outros',
                'slug'           => str_slug('Outros'),
                'animal_type_id' => 4,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            # 5 - Peixes
            [
                'id'             => 31,
                'name'           => 'Acara',
                'slug'           => str_slug('Acara'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 32,
                'name'           => 'Acara Bandeira',
                'slug'           => str_slug('Acara Bandeira'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 33,
                'name'           => 'Beta',
                'slug'           => str_slug('Beta'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 34,
                'name'           => 'Carpa',
                'slug'           => str_slug('Carpa'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 35,
                'name'           => 'Cascudos',
                'slug'           => str_slug('Cascudos'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 36,
                'name'           => 'Coridoras',
                'slug'           => str_slug('Coridoras'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 37,
                'name'           => 'Dourado',
                'slug'           => str_slug('Dourado'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 38,
                'name'           => 'Jaú',
                'slug'           => str_slug('Jaú'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 39,
                'name'           => 'Kinguio',
                'slug'           => str_slug('Kinguio'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 40,
                'name'           => 'Molinesia',
                'slug'           => str_slug('Molinesia'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 41,
                'name'           => 'Peixe-palhaço',
                'slug'           => str_slug('Peixe-palhaço'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 42,
                'name'           => 'Piraiba',
                'slug'           => str_slug('Piraiba'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 43,
                'name'           => 'Pirarucu',
                'slug'           => str_slug('Pirarucu'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 44,
                'name'           => 'Tambaqui',
                'slug'           => str_slug('Tambaqui'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 45,
                'name'           => 'Outros',
                'slug'           => str_slug('Outros'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            # 6 - Reptil
            [
                'id'             => 46,
                'name'           => 'Cobra',
                'slug'           => str_slug('Cobra'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 47,
                'name'           => 'Cagadu',
                'slug'           => str_slug('Cagadu'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 48,
                'name'           => 'Jabuti',
                'slug'           => str_slug('Jabuti'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 49,
                'name'           => 'Lagarto',
                'slug'           => str_slug('Lagarto'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 50,
                'name'           => 'Tartaruga',
                'slug'           => str_slug('Tartaruga'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'id'             => 51,
                'name'           => 'Outros',
                'slug'           => str_slug('Outros'),
                'animal_type_id' => 5,
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}
